CREATE SEQUENCE orders_order#_seq 
INCREMENT BY 1 
START WITH 1021 
NOCACHE
NOCYCLE;
SELECT * FROM USER_SEQUENCES;
SELECT * FROM USER_OBJECTS 
WHERE object_type='SEQUENCE';
SELECT * FROM ORDERS;
INSERT INTO ORDERS(ORDER#,CUSTOMER#,ORDERDATE,SHIPDATE,SHIPSTREET,SHIPCITY,SHIPSTATE,SHIPZIP)
VALUES(ORDERS_ORDER#_SEQ.nextval,1010,'06-APR-09',NULL,'123 WEST MAIN','ATLANTA','GA',30418);
SELECT * FROM orderitems;
INSERT INTO orderitems(ORDER#,ITEM#,ISBN,QUANTITY,PAIDEACH) VALUES(ORDERS_ORDER#_SEQ.CURRVAL,1,3437212490,1,20);
COMMIT;
SELECT * FROM ORDERS;
ALTER SEQUENCE ORDERS_ORDER#_SEQ
INCREMENT BY 10;
DROP SEQUENCE ORDERS_ORDER#_SEQ;

--INDEXES MAP OF COLUMN VALUES AND ROW ID OF MATCHING COLUMNS
--USED TO FACILITATE QUERIES BY STORING THE REFERNCES ON VALUES OR PRIMARY KEYS--
CREATE TABLE TEST_IDENTITY (COL1 NUMBER GENERATED AS IDENTITY PRIMARY KEY,COL2 NUMBER);
INSERT INTO TEST_IDENTITY(COL2) VALUES (355);
INSERT INTO TEST_IDENTITY(COL1,COL2) VALUES (222,350);
SELECT * FROM test_identity;
INSERT INTO TEST_IDENTITY(COL1,COL2) VALUES (DEFAULT,350);
COMMIT;
--Run the queries with explain plan
SELECT rowid,col1,col2 FROM test_identity where col1=1;
select * from employees e where e.first_name='John';
select * from employees e where e.salary>89;
SELECT * FROM CUSTOMERS; --CARDINALITY 20 COST 3
SELECT * FROM CUSTOMERS WHERE ZIP=2001;
SELECT * FROM CUSTOMERS WHERE REGION='W';
--create indexes
CREATE INDEX CUSTOMERS_INDEX_IDX ON CUSTOMERS(ZIP);
CREATE BITMAP INDEX CUSTOMERS_REGION_IDX ON CUSTOMERS(REGION);
CREATE INDEX BOOKS_PROFIT_IDX ON BOOKS(RETAIL-COST);
CREATE INDEX ORDERS_SHIPDATE_IDX ON ORDERS(NVL(SHIPDATE,'1-DEC-2023'));
CREATE UNIQUE INDEX BOOKS_TITLE_IDX ON BOOKS(TITLE);
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS WHERE COLUMN_NAME='REGION';
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME='CUSTOMERS';
SELECT * FROM USER_IND_COLUMNS WHERE TABLE_NAME='BOOKS';
--DROP INDEX
DROP INDEX BOOKS_PROFIT_IDX;
--CREATING PUBLIC SYNONYM SHOULD BE DONE WITH DBA PRIVILEGES
CREATE PUBLIC SYNONYM CUSTOMERS_PUBLIC FOR CUSTOMERS;
CREATE  SYNONYM CUSTOMERS_SYN FOR CUSTOMERS;
--CREATING VIEWS
SELECT * FROM BOOKS;
CREATE VIEW INVENTORY
AS SELECT ISBN,TITLE,RETAIL PRICE FROM BOOKS;
--COMPLEX VIEWS
CREATE VIEW PRICES
AS SELECT ISBN,TITLE,RETAIL,COST,RETAIL-COST PROFIT FROM BOOKS;
SELECT * FROM PRICES WHERE TITLE LIKE '%MICKEY%';
UPDATE PRICES SET RETAIL=29.5 WHERE TITLE LIKE '%MICKEY%';

CREATE OR REPLACE VIEW PRICES
AS SELECT ISBN, TITLE, RETAIL, COST,RETAIL-COST PROFIT,NAME FROM BOOKS
JOIN PUBLISHER USING(PUBID);

UPDATE PRICES SET NAME=' ';
SELECT TITLE,PROFIT FROM
( SELECT ISBN,TITLE,RETAIL,COST,RETAIL-COST PROFIT FROM BOOKS ORDER BY RETAIL-COST DESC)
WHERE ROWNUM<5;

SELECT TITLE,RETAIL-COST PROFIT FROM BOOKS ORDER BY PROFIT
FETCH FIRST 2 ROWS ONLY;
SELECT TITLE,RETAIL-COST PROFIT FROM BOOKS ORDER BY PROFIT
FETCH FIRST 25 PERCENT ROWS ONLY;